### ISSUE TITLE
Current version is suitable for production or not?

### ISSUE THREAD

**Issue by glinft** [akscf/mod_google_asr#1]
Hi, akscf,
I want to know how about Google ASR latency?
Could you explain more details?

**Comment by aks-tel** [comment]
Hi, 
> I want to know how about Google ASR latency?
honestly speaking i've done it only for the risk covering if something going wrong with whisper/openai and have never tasted it yet)
but one of the project we use google tts and it gives quite good results (working 24/7, around 2+ years), flight is normal.

>Could you explain more details?
will try, asking

**Comment by glinft** [comment]
> but one of the project we use google tts and it gives quite good results (working 24/7, around 2+ years), flight is normal.

How about mod_google_asr? As good as mod_google_tts?

**Comment by aks-tel** [comment]
maybe, not test yet) 
About the google_tts, I meant it has a low latency (less than 1s) and i might guess that ASR will show the same results but have no time to test it now)
